name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:latest
                options: --entrypoint "redis-server"
                ports:
                    - 6380:6370
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Setup Docker
              uses: docker/setup-buildx-action@v4

            - name: Cache Docker Layers
              uses: actions/cache@v3
              with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-buildx-
            - name: Install Docker Compose
              run: |
                mkdir -p $HOME/.docker/cli-plugins
                curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64 -o $HOME/.docker/cli-plugins/docker-compose
                chmod +x $HOME/.docker/cli-plugins/docker-compose
                docker compose version
            
            - name: Build Docker Compose
              run: |
                docker compose build
            
            - name: Start Docker Service
              run: |
                docker compose up -d